src/components/Settings/Settings.jsx

Rebased to fix conflict in https://github.com/jina-ai/dashboard/pull/34

Rebased to fix conflict in PR #34

---

dev-resources/dataStructures.js
dev-resources/testServer.js
src/components/LogStream/ChartBase.jsx
src/components/LogStream/LogLevelPieChart.jsx
src/components/LogStream/LogLevelSummaryChart.jsx
src/flux/store.js
src/views/LogsView.jsx

- add card titles to charts
- add x/y axis labels
- move legend to top
- adjust: hit radius, paddings, maxRotation, maxTicksLimit

Feat add chart labels

---

src/components/Common/HelpCard.jsx

This PR fixes #45. 
Added the support for opening links in the new tab.

fix: fix links open in new tab

---

src/views/LogsView.jsx

my bad. I forgot to pass the listener fn to the cleanup.

fix: add missing argument to cleanup fn

---

src/views/PackageView.jsx

getData() has been removed: https://github.com/jina-ai/dashboard/commit/621f83519828ac32cbf18ab9afdf8db5c5aa024d#diff-d51fd7d92be3d407da20f154173673b4L51-L55

fix: remove undefined function

---

src/data/flowTestData.js
src/helpers.js
src/helpers.test.js
src/views/FlowView.jsx

it's hacky code. it would be good to have a 2nd pair of eyes check throughly.

Jinadash 121 pods can only be connected one way and there seems to be a hick up when dragging the pods on the canvas

---

src/App.css
src/components/Common/MultiFilterSelect.tsx
src/components/LogStream/LogsTable.tsx
src/components/LogStream/LogsTableHeader.tsx

Added:
- table headers
- update logstream area style
-  `cursor:pointer` to `MultiFilterSelect`
- empty message when no logs present

Feat table headers

---

src/helpers.js
src/helpers.test.js

- add tests for formatSeconds and formatBytes
- refactor functions formatSeconds and formatBytes
- fix bug in formatBytes where convertion to KB was wrong

test(helpers): add tests for helper functions

---

.gitignore
cypress.json
cypress/fixtures/example.json
cypress/integration/views/flowview.js
cypress/plugins/index.js
cypress/support/commands.js
cypress/support/index.js
package-lock.json
package.json

This is an example implementation of an integration test with Cypress and the Jina Dashboard.
It tests if a connected dev server is displayed, the correct flow chart is rendered and if every pod of a new flowchart can be pulled from the sidebar.
A graphical test interface can be started with `npm run cy:dev`
The tests can be run with  `npm run cy:run`

Feature: Cypress

---

src/components/Common/HelpCard.tsx
src/views/NotFound.tsx

fix: solve view issues on home page

---

src/components/Task/BarChartCard.tsx
src/views/TaskView.tsx

fix: solve view issues on task page

---

.github/workflows/deploy-hub.yml
.github/workflows/deploy.yml

Todo: Discuss with team about minor, major versioning.

chore: add step in deploy workflows to bump version

---

src/components/Settings/FormItem.tsx
src/components/Settings/Settings.tsx
src/components/Settings/options.ts
src/redux/flows/flows.reducer.ts
src/redux/flows/flows.types.ts
src/redux/index.ts
src/redux/settings/settings.actions.ts
src/redux/settings/settings.constants.ts
src/redux/settings/settings.reducer.ts
src/redux/settings/settings.selectors.ts
src/redux/settings/settings.test.ts
src/redux/settings/settings.testData.ts
src/redux/settings/settings.types.ts

Feat redux settings integration

---

.github/workflows/label-pr.yml

It was failing in CI and not sure what it's doing. let's put it back when we need it.

Remove actions/labler

---

src/layouts/HubLayout.tsx
src/layouts/IconSidebar.tsx

Refactor HubLayout and IconSidebar to functional components

Refactor: Hublayout and IconSideBar to funcComponents

---

package-lock.json
package.json
src/flux/api.ts
src/redux/global/global.types.ts
src/redux/index.ts
src/redux/task/task.actions.ts
src/redux/task/task.constants.ts
src/redux/task/task.reducer.ts
src/redux/task/task.selectors.ts
src/redux/task/task.test.ts
src/redux/task/task.testData.ts
src/redux/task/task.types.ts
src/views/TaskView.tsx

Feat: redux task integration

---

cypress/integration/views/helpView.ts
src/components/Common/HelpCard.tsx
src/views/NotFound.tsx

- add data-name attribute to help card in HelpCard.tsx file
- add helpView.ts file to cypress/integration/views/ with cypress test

test: add integration test for help view

---

README.md

- added basic jinad instructions
- remove deprecated instructions

docs: remove deprecated content

---

src/components/FlowChart/CommandBar.tsx
src/layouts/IconSidebar.tsx

This is just a shallow fix and we need to fix the importYaml function

Fix: Import Yaml Bug

---

package.json
src/index.tsx

fix: change start script to run dashboard on windows

---

dev-resources/testServer.js

This follows my comment in https://github.com/jina-ai/dashboard/pull/140#discussion_r568469813

Fix clearline to work in ci

---

src/components/FlowChart/CommandBar.tsx

I need to record the gifs for the docs on dashboard.jina.ai, so I make style changes in this PR

Flow: Fixes

---

src/flux/store.ts
src/helpers/format.ts
src/redux/flows/flows.reducer.ts

The website shouldn't crash if someone enters invalid yaml

Fix: Add error handling to parseYAML

---

cypress/integration/visual-tests/flowDesign.ts

I tried to create connections with in, out ports, but that didn't work as I planned. 
Now, I'm using co-ordinates in the canvas to do it.
I'm not putting too much effort into this as we are changing flowchart library.

test: create snapshot test for flow design

---

netlify.toml

only build on netlify when there is a change in src directory

ci: add netlify.toml with build ignore

---

src/components/Styleguide/__snapshots__/TypographyPage.test.tsx.snap
src/helpers/tests/utils.test.ts
src/helpers/utils.ts
src/redux/flows/flows.actions.ts
src/redux/logStream/logStream.actions.ts
src/services/config.ts
src/services/jinad.ts
src/services/tests/jinad.test.ts
src/services/tests/jinad.testData.ts

- After starting flow, start loop to check if logs directory has been created\
- configurable delay and number of retries
- tests

feat: connection auto-refresh

---

src/components/Hub/HubOverviewAction.tsx

In ActionButton, switched color to use color from theme palette.

style(hub): change to color from theme

---

.github/workflows/ci.yml
cypress/plugins/index.js
cypress/support/index.ts
package-lock.json
package.json

Add cypress-instrument-cra for instrumenting code in dev environment
Register cypress-instrument-cra as a cypress plugin
Print integration test coverage in CI

test: use cypress coverage to get coverage of integration tests

---

src/index.tsx
src/views/FallbackPage.tsx

This PR should finally fix issues with old local storage. If we publish breaking changes, we can bump the version and this will trigger deletion of localStorage

feat: version control

---

.github/workflows/deploy-hub.yml
.github/workflows/deploy.yml
README.md
deployment.md

I'll merge this after subdomain for staging environment has been setup in cloudflare.

docs: create deployment documentation

---

src/components/FlowChart/FlowChart.tsx
src/components/FlowChart/SidebarItem.tsx

This PR should resolve 
https://github.com/jina-ai/dashboard/issues/273

Fix: multiple pods bug

---

.github/workflows/stale.yml

Exempt the issues with the label of `good first issue` from being closed by `stale-action`
**Docs**
**Tests**
**Typing**
**Styling**

feat: add exempts for the stale action

---

cypress.json
cypress/integration/views/flowview.ts
cypress/integration/views/logsView.ts
src/components/LogStream/LogsTable.tsx

**Docs**
**Tests**
**Typing**
**Styling**

test: add integration tests for logstream logs

---

src/index.tsx

**Docs**
**Tests**
**Typing**
**Styling**

chore: disable sentry in local and testing environments

---

cypress/integration/visual-tests/flowDesign.ts
src/components/Common/InfoToast.tsx
src/layouts/HubLayout.tsx
src/layouts/IconSidebar.tsx
src/redux/global/global.constants.ts
src/redux/global/global.reducer.ts
src/redux/global/global.selectors.ts
src/redux/global/global.test.ts
src/redux/global/global.types.ts

This PR fixes the https://github.com/jina-ai/dashboard/issues/271 issue.
**Docs**
**Tests**
**Typing**
**Styling**

feat: stack banners

---

cypress/integration/views/podView.ts
dev-resources/sample-data/args-flow.json
dev-resources/sample-data/args-pea.json
dev-resources/sample-data/args-pod.json
src/helpers/tests/flow-chart.testData.ts
src/modals/PodEdit.tsx

My first PR which targets to fix the issue #243 .
A couple of things need to be clarified:
- Two UI frameworks "react-bootstrap" and "shards-react" are being used in the repo, which is a bit overlapping; I wonder which one is recommended?
- Are there any tests that I could add/update in terms of the feature targeted in the PR? I couldn't see the tests regarding this specific component. Where can I find them? Does this PR require to add integration tests?
Thanks in advance.
**Docs**
**Tests**
**Typing**
**Styling**

feat(pod): change pod boolean props UI to switch button (issue #243)

---

src/services/multiModalScript.ts

**Docs**
**Tests**
**Typing**
**Styling**

Feat: Send gateway port to multi-modal frontend

---

README.md

**Docs**
**Tests**
**Typing**
**Styling**

docs(readme): rm missing eah god image link

---

.github/pull_request_template.md

Add items for replicating visual designs

---

src/components/Hub/HubNavigationBar.tsx
src/components/Styleguide/__snapshots__/ColorsPage.test.tsx.snap
src/emotion.d.ts
src/index.tsx
src/theme.ts
src/views/HubView.tsx

A simple nav bar for hub
**Docs**
- [X ] If you added new code; is it self documenting? (all the variable names clear, comments added where appropriate)
**Tests**
**Typing**
**Styling**

Feat: hub-nav-bar

---

src/components/FlowChart/ChartNode.tsx
src/components/Hub/HubOverviewAction.tsx
src/components/Hub/__snapshots__/HubOverviewActionsContainer.test.tsx.snap
src/components/LogStream/levels.ts

Add missing adjustments for the theming object merge
**Docs**
**Tests**
**Typing**
**Styling**

fix: palette bugs

---

.github/workflows/stale.yml

increasee the days before stale
**Docs**
**Tests**
**Typing**
**Styling**

feat: increasee the days before stale

---

src/components/Hub/CodeSnippetWithCopy.tsx

**Docs**
**Tests**
**Typing**
**Styling**

fix(snackbar): fix the snackbar close operation once it is opened

---

.github/workflows/deploy-swaggerui.yml

**Docs**
**Tests**
**Typing**
**Styling**

ci: push swagger build

---

.github/workflows/deploy-swaggerui.yml

**Docs**
**Tests**
**Typing**
**Styling**

fix: update deploy command

---

src/components/DebuggingTool/FlowChartNodes.tsx

**Docs**
**Tests**
**Typing**
**Styling**

fix: rm default to video

---

src/components/DebuggingTool/CustomRequestBodyEditor.tsx
src/components/DebuggingTool/Request.tsx
src/helpers/tests/utils.test.ts
src/helpers/utils.ts

**Docs**
**Tests**
**Typing**
**Styling**

Feat: example values as placeholders to additional fields

---

src/components/LogStream/LogsTableHeader.tsx
tailwind.config.js

**Docs**
- [ x] If you touched existing code; did you refactor existing naming, added comments where necessary?
**Tests**
**Typing**
**Styling**

fix(LogsTableHeader): fix header style of LogsTableHeader

---

src/components/DebuggingTool/FlowChartNodes.tsx
src/components/DebuggingTool/Matches.tsx
src/components/FlowChart/FlowChart.tsx

**Docs**
**Tests**
**Typing**
**Styling**

fix: layout in swagger ui
